A AUR package generator, that generates (duh) aur packages of your rust applications.

* Installation:
`cargo install cargo-makepkg`

* Usage:
Run `cargo makepkg` in the root of your rust application.

If you haven't set the values, in the toml file, cargo-makepkg will ask you some questions, that you have to answer.

This will create a new folder in /target called `aur-package` with a MAKEPKG, and a hidden SRCINFO file.

You definitly should test this makepkg file with
```
cd target/aur-package
makepkg -si
```
And edit it to your needs.

All you now have to do, is push the git repo in that dir, onto the aur.
You can do that, by doing the following:
- create a account on the aur
- add your public ssh key
- run `git remote add origin ssh://aur@aur.archlinux.org/<pkgbase>.git` (replace '<pkgbase>', with the name)
- run `git fetch`
- and then push the git repo `git push -u remote origin`
More info about that, can be found here: https://wiki.archlinux.org/index.php/AUR_submission_guidelines#Submitting_packages


* Alternatives
This is basically a fork of this: https://github.com/kstep/cargo-pkgbuild/
and similar to this:
https://github.com/fosskers/cargo-aur

The only difference to cargo-pkgbuild is that you don't have to have keep rust installed for it to work and the difference to cargo-aur is, that this isn't a binary package, but a source based one.
